### ISSUE TITLE
Allow expanding and collapsing of collections

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#106]
With the purpose of moving between abstractions more easily.

# Styling
- [ ] size increases with #nodes in it
- [x] Has a unique colour
- [x] Has same colour as its containing nos

# Change to NodeGraph
- [x] should fetch both nodes and collections (immediate neighbours) of the collection
    - [x] the nodes in the collection
    - [x] the child collections

- [x] a new node type to render in NodeGraph: "collection"
    - [ ] should have a bigger radius then normal nodes (based on number of nodes in the collection)
    - [x] should implement different mode actions (the 4 described below)

# The 4 modes
## View
Navigate to the collection editor. This will probably function as more of a summary of the subject. For example, what I do in _derivates_ now (it points to other different parts of derivative).
- [x] **For nodes**: Navigate to the node editor
- [x] **For collections**: Navigate to the collection editor (the same really)
    - [ ] Q: should links to "child nodes" and "related nodes" be represented differently?

### collection
- [x] modify name
- [ ] Ability to "promote" a node to a collection and "demote" a collection to a node
     - [ ] Promote: make the node a collection and change all edges to other nodes to be a "collection edge"
        - [ ] Move all :IN edges source to be the collection
        - [ ] Allow user to select the nodes which they want to be collapsed into the collection
     - [ ] Demote: Make the collection a node and change all edges to other nodes to be "normal edges"
        - [ ] move all :IN edges source to be the parent collection
- [x] Collection overview now shows hierarchies of collections implied by moving between abstractions

### edges
Allow the user to create edges between nodes (this includes collections).
Q: It is preferable to create an edge from node->node instead of col->node. How can this be made easy?
- [x] **Collection -> Collection**: treat both as nodes (ask if the user wants to connect to a specific node in the target collection?)
- [x] **Collection -> Node**: create a normal link
- [x] **Node -> Collection**: treat both as nodes (ask if the user wants to connect to a specific node in the target collection?)
- [x] **Node -> Node**: create a normal link

## Focus
This will "follow" the collection and focus on this collection as an abstraction
- [ ] **For nodes**: center the node
- [ ] **For collections**: focus on the collection as abstraction

## Expand (fetch)
This will "expand" the nodes by displaying the collection as a node and displaying all edges between the nodes
- [ ] **For nodes**: Fetch related nodes (edges with this node as a source)
- [x] **For collection**: Expand the collection
    - [x] Show outside of the graph in a list

Q: how to collapse again? A: click on the "collection node"
Q: How to make collapse permanent?
Q: should collapsed state be persisted?

# Routing
- [x] **/app/collections/**: The collection overview graph
- [x] **/app/collections/:id/nodes**: Show nodes and collections in the collection
- [ ] **/app/collections/:id/nodes/:id** Focus from within the collection graph (allows undo of focus)
- [ ] **/app/nodes/:id** Focus from within search

# Edge cases
- [ ] A collection without any nodes should not be displayed in the graph, just in the collection overview
- [ ] How to handle nodes that are in multiple collections?
* a collection should always consist of 2 or more nodes?

**Comment by Ri73** [comment]
> Size increases with #nodes in it
What if size increases with the total number of characters of the nodes in it? That would be more representative.

**Comment by bryanph** [comment]
Good suggestion, that would be more representative indeed, thanks.

**Comment by bryanph** [comment]
This is implemented in the redesign branche, will close for now.
