### ISSUE TITLE
"Keyboard Shortcuts" covering the text

### ISSUE THREAD

**Issue by Ri73** [bryanph/Geist#109]
When the "Keyboard Shortcuts" panel covers the end of an article it's not possible to scroll down to uncover it.
Also it's hard to distinguish if the text box is selected or if text cursor is further down. Maybe the boundaries of the text box could change somehow to indicate it's selected. Like GitHub's editor.

**Comment by bryanph** [comment]
Thanks, will add this to the list of changes.
What do you mean by "changing the boundaries of the text box"?

**Comment by Ri73** [comment]
While not selected
![not-selected](https://user-images.githubusercontent.com/12220708/28548187-f61fe0f2-70a8-11e7-973d-93d070aa614e.png)
While selected
![selected](https://user-images.githubusercontent.com/12220708/28548240-42a186a6-70a9-11e7-8b29-ff0dbce7cf7c.png)

**Comment by Ri73** [comment]
English is not my native language, so thanks for the patience ;)

**Comment by bryanph** [comment]
ah yes that makes sense, sin problema :)

**Comment by bryanph** [comment]
Will keep this in mind when re-implementing #121
