### ISSUE TITLE
Make AbstractionList hierarchical

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#124]
This might have quite poor performance with the current data structure

**Comment by erros84** [comment]
When I browse your Geist.fyi, I see major progress on dragging and dropping connections, but I'll admit I am quite lost. I understand that you now have a Base Node, but I can't get back to this view without returning to https://www.geist.fyi/app/. 

I liked the collections and the way that one node could be in multiple collections, but I'm lost now. I apparently don't understand the Abstraction button, it seems to "demote" a collection to a node, is that right? After having clicked it on the test project on Geist.fyi, I wish I hadn't. Now I can't figure out how to add a new collection if "Add Collection" is missing from below the Title.

The Focus feature allows me to Explore nearby nodes like the previous version, but clicking Explore in the node leaves me in "navigate" mode, which I would call "Edit" mode. "Edit" mode seems to be Add mode, which assumes that I want to create a backwards connection from where I am. I can't figure out how to create an unconnected node as before.

It's interesting that I seem to have the opposite idea of the directionality of the nodes. My database is organized in this way:
Object -> Subcategory -> Category -> Collection -> Database.
This object belongs in a subcategory, and this subcategory belongs to a supercategory, and this supercategory belongs to a collection, and the collection belongs to a database. Reversing the arrows seems backwards to me, and I would rather have objects pointing to the Database (like folders) and not the Database pointing to the Collections. I tend to add a detail with no links, and then link it to other nodes that categorize it. Part of this is that the Categories are the things I remember, and it is easier to add a link towards a category than to list all of the particulars. Ideally, the root node would point to notihing, and all nodes would eventually point to the root node.

Lastly...what in the world is the crop button?

Again, I realize that this is beta, but I'm just confused.

**Comment by bryanph** [comment]
Hey @erros84, thanks for your comment.
I'll try to give some reasons for the changes I made below.

# Some driving ideas about the changes I made:
* Be able to refer to "my personal knowledge base" as one continuous network. This is why I decided to connect every disconnected collection to the root collection.
* Blur the distinction between a node and a collection. Basically the goal is that all nodes are of type NODE and any node becomes a collection simply by adding "children" to it.
* When linking from a given node x to the "child" y_1 of a collection y_0, this basically means there is a connection between x -> y_1 (the explicit link) and x -> y_0 (an implicit link).  

# To respond to some of your other questions
## Demote button
I removed this behaviour of the clicking to demote before because I realized it wasn't really intuitive (like you say here). Are you running it locally? The abstracting works by dragging one node to another, then the one being dragged over becomes a collection and the node being dragged becomes part of that collection
## not being able to add a collection
I realized this too and added an issue for it here #123 
For now adding a collection is done by dragging a node over another node in "abstract" mode.
## naming of modes
Yes you're right, "edit mode" is more of an "add mode" indeed. Maybe we can discuss this to get more sensible modes in the explore page. If you wish you can create an issue for this.
## creating an unconnected node
This is done now by clicking the + button in the top menu bar. This makes it disconnected. I did this behaviour in the explore graph because it fetches nodes that are connected to the node and if adding a new node in this graph were not connected to any node it wouldn't show up. 
## on directionality of nodes
I'm not sure what you mean by this. The direction is as you said, like Object -> Subcategory -> Category -> Collection -> Database. 
This is represented internally by the :AbstractEdge type of edge. This is the edge that gets created when you add a "node" to a "collection" (or "abstraction"). 

# Closing words
That being said, I understand your confusion. If you wish I'd love to involve you more in these kinds of design decisions. Would be good for me to get some feedback and other people's views on these issues. It is kind of uncharted territory and I'm figuring it out as I go forward at the moment.

Also, I want to say that nothing is holy here with regards to functionality. If you think some decisions are bad or you have an alternative better solution, I'd love to hear it. I'll see if I can set up a chat service to make direct discussion easier. I appreciate the feedback, thanks for your honesty.
