### ISSUE TITLE
Allow any node to be the base of a collection

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#136]
Instead of having to explicitly convert to a collection. This will probably mean that no distinction will be made between Nodes and Collections. So their definitions are then like this:
* Node: a node with no children
* Collection: a node with 1 or more children

Tasks:
- [ ] Change all collection labels to just consist of using the AbstractEdge as identification of a collection
- [ ] Remove all convertToCollection calls
- [ ] Allow user to "zoom in" from any view - this should be the new functionality of the "focus" button
- [ ] Need to rewrite the Collection.getAll method since it relies on the Collection label

**Comment by erros84** [comment]
If you go too far this way...you will lose the idea of collections, and everything will become strictly hierarchical. Above all, I would like each node to continue to be in more than one collection, and the "add collection" feature is still broken in the new version,

**Comment by bryanph** [comment]
This blurs the distinction between a node and a collection indeed, but it doesn't make it hierarchical actually. You can still link arbitrarily, it's just that any node can "act" as a collection by placing nodes "under it" instead of making a direct link. This retains the collection aspect.

So the idea is that for adding a "collection" of things, you would now just create a node, give it a name and "focus in" on the node and start adding nodes. 

This also retains the functionality of adding a node to multiple "collections". If you want to show multiple collections together in the same view, you can add them to a container collection and expand them.
