### ISSUE TITLE
When expanding an abstraction, only show nodes that are connected to any nodes in the parent graph

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#141]
Right now when expanding a collection it shows all underlying nodes and in the process creates many "node islands". The most common use case in expanding for me is to see how the existing nodes in the graph connect to the underlying nodes of the abstraction.

**Comment by erros84** [comment]
I want to see the "node islands" the way they showed up in the earlier version. I loved the fact that collections were metadata and not true connections. For me, navigating through connections will only show linked stuff, but navigating by collection shows categories of things that may not yet be connected. This is my "projects" collection, and not everything is connected:
![image](https://user-images.githubusercontent.com/986339/31234783-a9901e78-a9e7-11e7-96a3-5c71bda31f40.png)
If i'm looking for projects by a certain person, I can choose the person collection (metadata), then explore on the node i find for the person (connections).

**Comment by bryanph** [comment]
@erros84 
I agree, I was focusing too much on a specific use case when i wrote this. Sometimes it makes sense to want to expand a collection to only see how it connects to the nodes already visible. Maybe could be a toggle sometime in the future but probably not relevant for now. Thanks.
