### ISSUE TITLE
When adding a dual link both ways, the nodes fly apart

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#35]
Probably due to the old link not changing from straight to curved upon doing this

**Comment by erros84** [comment]
I just experienced this bug today with a cluster of double-linked nodes...maybe it's not fixed.

**Comment by bryanph** [comment]
i reopened it. It is because the edges overlap which makes the force
simulation go ape shit.

2017-08-04 3:16 GMT+02:00 erros84 <notifications@github.com>:
