### ISSUE TITLE
Email account verification is not working

### ISSUE THREAD

**Issue by mageru** [bryanph/Geist#59]
When I click the validation email it either returns a JSON error (can't get it to do this again, link must have expired? also the error happened on mobile) or returns me to the validate your email prompt (asking for email, I put in my email and click "Resend Email" but nothing happens).

**Comment by bryanph** [comment]
Woops! You seem to be right the validation email is not sent when doing twitter authentication, i'll try and fix this as soon as possible. Thanks for the notice!

**Comment by bryanph** [comment]
Should be fixed in 539332d097bbb4c3d73a7edc1ed72e3c4a7c095c
