### ISSUE TITLE
Log in Emails Verification flow doesn't work

### ISSUE THREAD

**Issue by thundergolfer** [bryanph/Geist#91]
### Steps To Reproduce

1. Go to https://www.geist.fyi/
2. Click "Twitter" to sign up with Twitter
3. Authorize the application

### Expected behaviour 

I receive a confirmation email at my Twitter email (which shouldn't really be necessary). Or when I enter an email and hit "Resend email" I should get an email at the entered email address.

### Actual Behaviour

No email

**Comment by thundergolfer** [comment]
**Update:**

I now have received an email to the email I entered in the "Resend email" box, but clicking on the "Log in now" button in that email just redirects me to https://www.geist.fyi/auth/account/verification

**Comment by bryanph** [comment]
Thanks for the detailed issue @thundergolfer. I wasn't aware twitter added user email to their API, i'll make sure to just use the email provided in the API without verification. 

With regards to the email, could you perhaps check if you got two separate emails (the welcome email should be sent later)? Or that one of them is in your spam box?

**Comment by bryanph** [comment]
Added in bryanph/full-auth-middleware@70492622ab27a730abd430337d05521f234b82a2
Should work as desired now

Again thanks for the notice @thundergolfer!
