### ISSUE TITLE
Missing modules for server/ ?

### ISSUE THREAD

**Issue by IniZio** [bryanph/Geist#94]
I forked the repo, however when i try to run the server with 'npm run dev' which launches both client and server, it seems like the dependencies needed in server/app.js including 'full-auth-middleware', 'jade', 'passport-facebook' are missing, also it seems to find jade templates while the views are actually '.hbs' files?

**Comment by bryanph** [comment]
Hey @IniZio,

I'm using this module here https://github.com/bryanph/full-auth-middleware for authentication which I am developing alongside this project. Therefore I had it "npm linked". I added the dependency through github for now.

To install right now you need to do the following:

## Dependencies
The versions here are just the ones I use at the moment, higher versions will probably work but not sure
* Mongodb 3.4.4
* neo4j 3.2.0
* elasticsearch 2.4.5 (should make this dependency optional)
* redis 3.0 (again, should be made optional)

## Config
Copy the sample config for authentication and configuration
`cp server/config/sample.config.js server/config/config.js`
`cp server/config/auth.sample.js server/config/auth.js`

By the way, I am working on a pretty major redesign in this branch https://github.com/bryanph/Geist/tree/feature/redesign

That should be it. Let me know if you run into any more install problems.

**Comment by IniZio** [comment]
I am not really sure if `scripts/etc/createESIndexes.sh` exists in the repo, and still the jade templates not existing are still causing problems to running the server.

Other than that, the dependencies and config problems were solved thanks!

**Comment by bryanph** [comment]
I changed the "authTemplate" option in auth.sample.js, can you verify this is set to "auth.hbs" in your config?
Oh and the script is in `scripts/ES/createESIndexes.sh`. If that script doesn't work, run the `scripts/cleanDB.sh` script first before trying again.
