### ISSUE TITLE
New design for NodeGraph

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#99]
Two modes:
* Explore mode
* Edit mode

# Both
- [x] put label at the bottom and set a max width after which multiple lines will be used
- [ ] put a limit on the size of a node label
- [ ] Create a hover state for nodes and edges (only in edit mode) (select should be bigger than the node) with a color
- [ ] When there are no nodes yet, start in edit mode
- [ ] Set the initial zoom without a transition and fade in nodes
* Indicate that an edge is set from within the content? How will explicit and implicit edges be handled?
- [x] make edges look less heavy

# Edit mode
- [x] Create a new node (click on canvas, should have a proper hover icon)
- [x] Create edge between nodes (drag node to another node)
- [x] Edit a node's title (click on the node)
- [ ] remove edge from graph
- [ ] remove node

# Explore mode
- [ ] Pull in "related nodes" from a node that has edges to nodes not yet in the graph. (a separate button)
- [ ] "Center a node": make this node the center of the graph (explore) and only show L1 nodes (allow a user to expand to L2)  (a separate button)
- [x] Open the node editor (click on node)

# other
- [ ] Visual indicator for a Node that has edges that can be expanded, not shown in the graph yet.
- [ ] Clicking this visual indicator should fetch these nodes and add them to the graph

## optional
- [ ] Dragging a node to a specific position should fix the node (explore)
- [ ] Double click on the node should remove the fixed position (explore)
- [ ] different sizes of a node based on (betweenness centrality, or other metrics?)
- [ ] two modes: 
1. drag and fix http://bl.ocks.org/norrs/2883411 https://bl.ocks.org/mbostock/3750558
2. drag and create an arrow http://bl.ocks.org/rkirsling/5001347
- [ ] store fixed state in the back-end along with position (can this be done? as long as aspect ratio is constant, yes.,

Only in SubjectDetailGraph:
- [ ] Show Subject title
- [ ] An "add node" button to add a new node to this graph

Only in NodeGraph:
- [ ]

# Centering node
* When clicking button, make it "active"
* When clicking on canvas, reset the focusMode
* when clicking on a node, call the centerNode action
* transition the selected node to the middle of the graph
* fetch L1 nodes
* let graph forces do the rest 

# difficulties
- when adding to collection, how to indicate adding an already existing node?
- when creating a relation, how to indicate creating a relation to a node that is not currently in the graph, but is in the pkb?

**Comment by erros84** [comment]
**Nodes containing docs**
It is hard to tell if a node contains a document. 
Could nodes with descriptions/documents show a thicker border.
Also, how hard would it be to have mouseover or right-click show a preview of the first lines of the document (see image)?
![popup](https://user-images.githubusercontent.com/986339/28923703-ca512246-7856-11e7-8152-b0e56087dfb8.png)

**Comment by bryanph** [comment]
Hey @erros84,
I actually want to make each node able to contain a "document" and of a collection of assets like links, video, images, etc. In my case I always have a document with each node. What is your use case for having nodes without documents? Are they like placeholders?

I like the idea of a preview although I am not quite sure what is a good way to do this with regards to UI, so for now it just navigates to the document directly.

**Comment by erros84** [comment]
Sometimes nodes are just reminders, and don't need more than a title.

Sometimes I just place a point for further research later. 

I do also use some structural placeholders to make navigation make sense, here's a use-case:

> I work with different projects in many (up to 70) languages across a country, I created placeholder nodes for each region of the country and linked them by geographic borders (nerd alert). When I work in a new language, I can add a node for the language (that will have further project nodes), and link it to the region. Regions are in a caregory called "Regions". Languages are in a Category called "Languages". In collections mode for Languages, they will appear disconnected, but in Explore mode, I can see all geographically-related languages together: Nearby Regions-Region-Languages .  

Other than the linguistic curiosity, I won't actually be doing research about each physical region, so they will remain descriptionless. Sometimes, the connection to a real concrete concept makes description unneccesary.

**Regions Collection**
![2017-08-04 01_12_59-photos](https://user-images.githubusercontent.com/986339/28949089-441a59b6-78b2-11e7-978a-bc6a588841cb.png)

**Exploring Ewondo Language's Connections:**
![ewo](https://user-images.githubusercontent.com/986339/28949440-c3bea4ae-78b4-11e7-8bc4-a32ec2951f33.png)

Languages: Yellow 
Geographic Regions: Blue 
Projects: green (These have descriptive documents.)

I'm intentionally limiting my collections to things of a type here, and carefully planned connections should eliminate the need for a "Region/Language/Project" supercollection.  So far, probably about half of my nodes are descriptionless, and these are split between structural placehoders, un-researched concepts/ideas, and people that form logical links between projects/concepts.

**Comment by erros84** [comment]
**Edit Mode: Remove Edge from Graph** is kind of a major necessary feature.
In the inbox, I find that I can double-click on an edge to delete it, or drag one note onto another to create an edge. Inside a collection, these do not work with the mouse, but at least there is an Add relation button.

To remove an edge inside a collection, one must either:
- Drop into Neo4j and use Cypher,
- Remove all Collections from both nodes and return to inbox to delete the link.
- Delete one of the nodes and recreate it.

**Comment by bryanph** [comment]
yes there will be a different mode that allows you to remove edges and nodes

2017-08-04 3:13 GMT+02:00 erros84 <notifications@github.com>:

**Comment by bryanph** [comment]
That is very clever, I like your approach! Yes placeholders do make sense, i'll make sure to add this to my list :)
